<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="S42826" encoding="ISO-8859-1" lastModifiedBy="bcladoveanu" flowName="/FRE_STD3_2_PEPPOL_BIS_Billing3.0_FI/Mapping Flows/project.mbflw" checksumTest="true" creationDate="02/09/2021 16:31:11 +0300" engineType="MB" lastModifiedDate="16/10/2024 14:59:05 +0300">
   <mappingInformations>
      <mappingInformation description="20210902 FN Created based upon FRE_STD3_2_PEPPOL_BIS_Billing3.0_SE.CDPAY-11784.\\n\\nArchive file list:\\nFRE_STD3_2_PEPPOL_BIS_Billing3.0_FI.prj\\nFRE_STD3_2_PEPPOL_BIS_Billing3.0_FI.rtm\\nFRE_STD3_PEPPOL3.0.adf\\nUBL_21_Invoice.adf\\nFRE_STD3_2_PEPPOL_BIS_Billing3.0_FI.x4\\nFRE_STD3_2_PEPPOL_BIS_Billing3.0_FI.vw1\\nFRE_STD3_2_PEPPOL_BIS_Billing3.0_FI.vw2\\nFRE_STD3_2_PEPPOL_BIS_Billing3.0_FI.map\\nDMnormal.mc\\n" state="Active" path="Maps/FRE_STD3_2_PEPPOL_BIS_Billing3.0_FI.map">
         <flow factoryType="FlowAdapter" mapFileName="~/Maps/FRE_STD3_2_PEPPOL_BIS_Billing3.0_FI.map" notUseingNamespace="true" codeFileName="~/DMnormal_b2bi.mc"/>
      </mappingInformation>
   </mappingInformations>
</project>